### ISSUE TITLE
Can't connect to server after starting container

### ISSUE THREAD

**Issue by GTP95** [silinternational/ssp-base#172]
Greetings,

I'm trying to use this Docker image for SimpleSAMLphp, but after following the instructions in the "local testing" section of the readme, I still can't connect to it using Firefox nor curl. Here is what I did in more detail:
I started by adding the following to my `docker-compose.yml`:
```yml
  identityprovider:
    image: silintl/ssp-base  # https://hub.docker.com/r/silintl/ssp-base
    ports:
      - 80:8080
    env_file:
      - identityprovider.env
 ```
I then downloaded the [local.env.dist](https://github.com/silinternational/ssp-base/blob/develop/local.env.dist) file and renamed it to `identityprovider.env`. Then I put inside that file values for `ADMIN_EMAIL`, `ADMIN_PASS`, `IDP_NAME`, `SECRET_SALT` and the optional GitHub token (inside `COMPOSER_AUTH`). I also set `LOGGING_LEVEL=DEBUG`.   
Finally, I tried to create and start the container with `docker-compose up -d identityprovider`. 
```
$ docker-compose logs -f identityprovider
docker-identityprovider-1  | PRETTY_NAME="Ubuntu 22.04.1 LTS"
docker-identityprovider-1  | PHP 8.1.2-1ubuntu2.11 (cli) (built: Feb 22 2023 22:56:18) (NTS)
docker-identityprovider-1  | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.22.0.2. Set the 'ServerName' directive globally to suppress this message
docker-identityprovider-1  | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.22.0.2. Set the 'ServerName' directive globally to suppress this message
docker-identityprovider-1  | [Thu May 04 14:07:15.343587 2023] [mpm_prefork:notice] [pid 14] AH00163: Apache/2.4.52 (Ubuntu) configured -- resuming normal operations
docker-identityprovider-1  | [Thu May 04 14:07:15.343623 2023] [core:notice] [pid 14] AH00094: Command line: '/usr/sbin/apache2 -D FOREGROUND'
```
But if I try to connect to the server on the exposed port I get:
```
$ curl localhost:8080
curl: (7) Failed to connect to localhost port 8080 after 1 ms: Couldn't connect to server
```
What could be the issue? 
Thank you for your help,

GTP95

**Comment by Baggerone** [comment]
@GTP95,
For docker-compose, the docs say this about `ports` ...
ports (HOST:CONTAINER)

If  you are doing `curl` from your computer, you would do `curl localhost:<the HOST port number>`, unless the HOST port number is just `80`, in which case you can ignore it.

If you are doing `curl` from within another container, you would do `curl identityprovider`.

**Comment by Baggerone** [comment]
Here's an example of how we use it (see the docker-compose.yml file)
https://github.com/silinternational/simplesamlphp-module-material

**Comment by GTP95** [comment]
I'm specifying the port because in my `docker-compose.yml` I forwarded the container's port 80 to my host's port 8080, as it is confirmed by:
```
$ docker ps
CONTAINER ID   IMAGE              COMMAND                  CREATED          STATUS         PORTS                                           NAMES
ce1ff0cf9a34   silintl/ssp-base   "/usr/local/bin/s3-e…"   46 minutes ago   Up 2 seconds   80/tcp, 0.0.0.0:80->8080/tcp, :::80->8080/tcp   docker-identityprovider-1
```
And btw if I use curl without specifying the port is still fails:
```
$ curl localhost
curl: (56) Recv failure: Connessione interrotta dal corrispondente
```
I'm using curl from my host.

**Comment by Baggerone** [comment]
@GTP95
In your docker-compose file, try changing the port to `"8080:80"` and then do `curl localhost:8080`.

**Comment by GTP95** [comment]
You're right, I got the port order swapped. Now I can connect, but I'm still getting an error. But at least now the error comes from the server, I'll see if I can figure that out. If not, I'll open a separate issue.
Thank you for your help!
